#!/bin/bash
# interactive (prompts for password) script for downloading 
# the raw genotype data from ftp-server ftpgeno.geno.no

ftpgeno=$(pwd | sed s/scripts$/ftpgeno/) #default location

echo -n "Path to download raw genotype data [$ftpgeno]:"; read ftpgenonew
if [ "$ftpgenonew" != "" ]; then ftpgeno=$ftpgenonew; fi
mkdir -p $ftpgeno
cd $ftpgeno

echo "Downloading raw genotype data in $ftpgeno"
wget -nv -nH -r ftp://avlgeno@ftpgeno.geno.no/*Raw_Data_Files --ask-password      	#get genotypes and pedigree files
wget -nv -nH -r ftp://avlgeno@ftpgeno.geno.no/Raw_Data_Files/affy_raw --ask-password	#Affymetrix data
ln -s Raw_Data_Files/affy_raw/* Raw_Data_Files/
