#!/bin/bash
#SBATCH --ntasks=1              # 1 core(CPU)
#SBATCH --nodes=1               # Use 1 node
#SBATCH --job-name=geno_imp  	# sensible name for the job
#SBATCH --mem-per-cpu=16G
#SBATCH --time=04:00:00
#SBATCH --account=nn4653k

module load R
. /usit/abel/u1/gjuvslan/geno/virtenv/bin/activate	#virtualenv with Python 2.7.10 and numpy 1.12.1

cd ..
pwd=$(pwd)

sed -n '/^```bash/,/^```/ p' < README.md | sed 's/^```bash/echo -n "Entering new code block: "; date/' | sed 's/^```//' > readmescript
sed -i '/^prefix=/s/.*/prefix=/' readmescript
sed -i "s#^prefix=#prefix=$pwd#" readmescript
sed -i '/^ftpgeno=/s/.*/ftpgeno=/' readmescript
sed -i "s#^ftpgeno=#ftpgeno=$pwd/ftpgeno#" readmescript
chmod 755 readmescript
./readmescript

